name: build esp32s3 demo
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1.2.0
      with:
        esp_idf_version: latest
        target: esp32s3
        esp_idf_docker_image: espressif/esp-matter
        command: cd /app/${{ github.repository }}/ && echo "==current dir==" && pwd && ls && idf.py build